
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    URUN_ADI = @"TOZ SEKER",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual KATEGORI_ADI with predicted KATEGORI_ADI from sample data...\n\n");


Console.WriteLine($"URUN_ADI: {@"TOZ SEKER"}");
Console.WriteLine($"KATEGORI_ADI: {@"İÇECEK"}");


Console.WriteLine($"\n\nPredicted KATEGORI_ADI: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

